name: lint

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v3
    - run: pip install --user codespell[toml] ruff
    - run: codespell -L manuel,Manuel --skip="*.bib"
    - name: Lint with ruff
      run: |
        # stop the build if there are Python syntax errors or undefined names
        ruff check . --output-format=github --line-length=200 --select=E501,E9,F63,F7,F82 --target-version=py38
        # exit-zero treats all errors as warnings
        ruff check . --exit-zero --line-length=200 --statistics
